Setup code coverage

diff --git a/c2cwsgiutils_run b/c2cwsgiutils_run
--- a/c2cwsgiutils_run
+++ b/c2cwsgiutils_run
@@ -4,17 +4,33 @@ then
     GUNICORN_PARAMS="-b :80 --worker-class gthread --threads 10 --workers 5"
 fi
 
-trap ctrl_c TERM INT
-function ctrl_c() {
-    echo "Caught a signal"
-    kill -SIGINT $PID
+_term() {
+    echo "Caught SIGTERM signal!"
+    kill -TERM "$child" 2>/dev/null
+    wait "$child"
     exit 1
 }
+
+_int() {
+    echo "Caught SIGINT signal!"
+    kill -INT "$child" 2>/dev/null
+    wait "$child"
+    exit 1
+}
+
+trap _term SIGTERM
+trap _int SIGINT
 
 while true
 do
     gunicorn $GUNICORN_PARAMS c2cwsgiutils.wsgi_app:application &
-    PID=$!
-    wait $PID
+    child=$!
+    wait "$child"
+    exit_status=$?
+    if [ $exit_status -eq 0 ]
+    then
+        exit 0
+    fi
+    echo "gunicorn exited with an error ($exit_status), restarting in 1s"
     sleep 1
 done
